#!/bin/bash
# A script to clone all necessary repos when installing from scratch. the $HBP need to be set-up for this script to work successfully

if [[ -z $HBP ]] ; then
  echo "Please set the \$HBP variable to your desired installation path first."
  exit
else
  if [[ -d $HBP ]] ; then
    echo "The NRP repos will be cloned to the already-existing directory" $HBP
  elif [[ -f $HBP ]] ; then
    echo "Invalid destination." $HBP "is a file."
    exit 1
  else
    echo "The NRP repos will be cloned to the newly created directory" $HBP
    mkdir -p -v $HBP
  fi
fi

# Get EPFL username to clone repos
echo
read -p "Enter your EPFL username: " user
echo

function clone_repo {

  if [ "$#" -ne 1 ] ; then
    echo "Invalid number of arguments to clone_repo. Aborting."
    exit 1
  fi

  echo
  echo $1
  if [ -d "$1" ] ; then
    echo "Skipped, directory already exists."
  else
    git clone ssh://$user@bbpcode.epfl.ch/neurorobotics/$1 && scp -p $user@bbpcode.epfl.ch:hooks/commit-msg $1/.git/hooks/
  fi
  echo
}

# cloning all repos
repos=(
    BrainSimulation
    bulletphysics
    CLE
    ExDBackend
    ExDFrontend
    ExperimentControl
    GazeboRosPackages
    gazebo
    gzweb
    Models
    MUSIC
    nest-simulator
    nrpBackendProxy
    retina
    sdformat
    VirtualCoach
)
echo "Cloning all repos:"
pushd $HBP > /dev/null
for repo in ${repos[@]} ; do clone_repo $repo ; done
popd > /dev/null