#!/bin/bash
# A script to clone all necessary repos when installing from scratch. the $HBP need to be set-up for this script to work successfully
#
# Upstream selection (EBR2-54). Default is Bitbucket; set
# NRP_UPSTREAM=github to clone from the vvorobjov/nrp-* mirrors.
#
#   NRP_UPSTREAM=bitbucket  (default)  bitbucket.org/hbpneurorobotics/<repo>.git
#   NRP_UPSTREAM=github                github.com/vvorobjov/nrp-<repo>.git
#                                      (the 'nrp-' prefix is added if the
#                                       bitbucket name doesn't already start
#                                       with 'nrp-')
#   NRP_UPSTREAM=<prefix-url>          <prefix-url>/<repo>.git
NRP_UPSTREAM="${NRP_UPSTREAM:-bitbucket}"

nrp_upstream_url() {
    local repo="$1"
    case "$NRP_UPSTREAM" in
        bitbucket)
            printf '%s\n' "https://bitbucket.org/hbpneurorobotics/${repo}.git"
            ;;
        github)
            local gh_name="$repo"
            case "$repo" in
                nrp-*) ;;
                *) gh_name="nrp-${repo}" ;;
            esac
            printf '%s\n' "https://github.com/vvorobjov/${gh_name}.git"
            ;;
        *)
            printf '%s\n' "${NRP_UPSTREAM%/}/${repo}.git"
            ;;
    esac
}

install_dir="$HBP"

if [[ -z "$install_dir" ]]; then
  echo "Please set the \$HBP variable to your desired installation path first."
  exit
else
  if [[ -d "$install_dir" ]]; then
    echo "The NRP repos will be cloned to the already-existing directory" "$install_dir"
  elif [[ -f "$install_dir" ]]; then
    echo "Invalid destination." "$install_dir" "is a file."
    exit 1
  else
    echo "The NRP repos will be cloned to the newly created directory" "$install_dir"
    mkdir -p -v "$install_dir"
  fi
fi

git_branch=$(git rev-parse --abbrev-ref HEAD)

function clone_repo() {

  [ "$#" -ne 1 ] && echo "Invalid number of arguments to clone_repo. Aborting." && exit 1

  echo
  echo "$1"
  if [ -d "$1" ]; then
    echo "Skipped, directory already exists."
  else
    repo_url=$(nrp_upstream_url "$1")
    if [ "$NRP_INSTALL_MODE" == "user" ]; then
      git clone -b master --depth 1 "$repo_url" "$1"
    else
      git clone "$repo_url" "$1"
      pushd "$1" >/dev/null
      git checkout "$git_branch" || git checkout development
      popd >/dev/null
    fi
  fi
  echo
}

# Cloning repos
option="$1"
source $( dirname -- "$0"; )/repos.txt

case $option in
backend)
  repos=(
    nrp-backend
    nrp-core
  )
  ;;
frontend)
  repos=(
    nrp-proxy
    nrp-frontend
  )
  ;;
*)
  repos=(
    ${nrp_repos[*]}
  )
  ;;
esac

echo "Cloning repos:"
pushd "$install_dir" >/dev/null
for repo in "${repos[@]}"; do
  clone_repo "$repo"
done

popd >/dev/null
