version: '3.0'

services:
  mqtt-broker-service:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ${HBP}/nrp-user-scripts/config_files/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    container_name: mqtt-broker

  haproxy-service:
    image: ${NRP_DOCKER_REGISTRY:-docker-registry.ebrains.eu/}nrp/nrp-core/nrp-haproxy${NRP_IMAGE_TAG}
    container_name: nrp-haproxy
    volumes:
      - ${HBP}/nrp-user-scripts/config_files/haproxy/local_docker/haproxy.docker.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${HBP}/nrp-user-scripts/config_files/haproxy/cors.lua:/usr/local/etc/haproxy/lua_scripts/cors.lua
    ports:
      - 9000:9000
    depends_on:
      - nrp-proxy-service

  nrp-frontend-service:
    image: ${NRP_DOCKER_REGISTRY:-docker-registry.ebrains.eu/}nrp/nrp-core/nrp-frontend${NRP_IMAGE_TAG}
    container_name: nrp-frontend
    # TODO: [NRRPLT-8789] Configuration not working
    # volumes:
      # - ${HBP}/nrp-user-scripts/config_files/nrp-frontend/config.json.local.docker:/nrp-frontend-app/build/config.json


  nrp-proxy-service:
    image: ${NRP_DOCKER_REGISTRY:-docker-registry.ebrains.eu/}nrp/nrp-core/nrp-proxy${NRP_IMAGE_TAG}
    container_name: nrp-proxy
    volumes:
      - ${HBP}/nrp-user-scripts/config_files/nrp-proxy/config.json.local.docker:/nrp-proxy-app/config.json
      # - ${HBP}/nrp-core/examples/templates:/nrp-templates
      - nrp-templates:/nrp-templates
      - ${STORAGE_PATH}:/nrpStorage
    depends_on:
      - nrp-backend-service

  nrp-backend-service:
    # image: ${NRP_DOCKER_REGISTRY:-docker-registry.ebrains.eu/}nrp/nrp-core/backend-nrp-opensim-tvb-ubuntu20${NRP_IMAGE_TAG}
    image: ${NRP_DOCKER_REGISTRY:-docker-registry.ebrains.eu/}nrp/nrp-core/backend-nrp-xpra-gazebo-nest-ubuntu20${NRP_IMAGE_TAG}
    container_name: nrp-backend
    environment:
      STORAGE_ADDRESS: nrp-haproxy
      STORAGE_PORT: 9000
      NRP_MQTT_BROKER_ADDRESS: mqtt-broker:1883
      NRP_XPRA_PORT: ${NRP_XPRA_PORT:-9876}
      NRP_DISPLAY: ${NRP_DISPLAY:-100}
    ports:
      - 9876:9876
    volumes:
      - ${HBP}/nrp-user-scripts/config_files/nginx.docker/uwsgi-nrp.ini:/usr/uwsgi-nrp.ini
      - ${HBP}/nrp-user-scripts/config_files/nginx.docker/nginx.conf:/etc/nginx/nginx.conf
      - ${HBP}/nrp-user-scripts/config_files/nginx.docker/conf.d/nrp-services.conf:/etc/nginx/conf.d/nrp-services.conf
      # - ${HBP}/nrp-core/examples/templates:/nrp-templates
      - nrp-templates:/nrp-templates

# You can specify your own Templates folder by nounting it instead of nrp-templates volume
volumes:
  nrp-templates:
