#!/bin/bash

if [ "$#" -lt 1 ]; then echo "Usage: nrp_cobertura_check <coverage_xml_file>"; exit 1; fi
if [ -z "$NRP_COVERAGE_BRANCH" ]; then echo "nrp_cobertura_check: NRP_COVERAGE_BRANCH is not set"; exit 1; fi
if [ -z "$NRP_COVERAGE_LINE" ]; then echo "nrp_cobertura_check: NRP_COVERAGE_LINE is not set"; exit 1; fi

coverage_file=$1

sudo apt-get update && sudo apt-get install -y libxml2-utils bc
covrate=$(xmllint --xpath "string(//coverage/@branch-rate)" $coverage_file) && covrate=$(bc <<< "$covrate * 100") && if (( $(bc <<< "$covrate < $NRP_COVERAGE_BRANCH") )); then echo "COVERAGE FAILED branch rate $covrate is lower than $NRP_COVERAGE_BRANCH";exit 1;else echo "COVERAGE branch rate is $covrate";fi
covrate=$(xmllint --xpath "string(//coverage/@line-rate)" $coverage_file) && covrate=$(bc <<< "$covrate * 100") && if (( $(bc <<< "$covrate < $NRP_COVERAGE_LINE") )); then echo "COVERAGE FAILED line rate $covrate is lower than $NRP_COVERAGE_LINE";exit 1;else echo "COVERAGE line rate is $covrate";fi
