#!/bin/bash

function backup() {
  targetfile=$1
  if [ -f $targetfile ]
  then
    index=$((ls $targetfile.bak* 2>/dev/null || echo bak) | sed -n "s/^.*bak\([0-9]*\).*$/0\1/p" | sort -n -r | head -1)
    if [ $index -gt 9 ]
    then
      printf "\033[1;33mYou have more than 10 backups of $targetfile. Would you like to purge them? (y/N)\033[0m\n"
      read -t 5 p
      if [ "$p" == "y" -o "$p" == "Y" ]; then rm -f $targetfile.bak*; index=0; fi
    fi
    mv -f $targetfile $targetfile.bak$(expr $index + 1)
    echo "  Backed up $targetfile.bak"$(expr $index + 1)
  fi
}


# Remove already existing config files that will be set-up using the configure_nrp script
echo "Removing existing config files for nginx, Haproxy, nrp-frontend, nrp-backend, nrp-proxy"
printf "\033[1;33mWould you like to NOT backup your local versions? (this also purges your existing backups) (y/N)\033[0m\n"
read -t 5 p
if [ "$p" == "y" -o "$p" == "Y" ]; then NOBACKUP=1;fi

if [ -f $HOME/.local/etc/init.d/nginx ]; then $HOME/.local/etc/init.d/nginx stop; fi
if [ -f $HOME/.local/etc/init.d/haproxy ]; then $HOME/.local/etc/init.d/haproxy stop; fi

rm -rf $HOME/.local/etc/nginx $HOME/.local/etc/init.d/nginx $HOME/.local/etc/default $HOME/nginx $HOME/.local/var/log/nginx $HOME/.opt/bbp
rm -rf $HOME/.local/etc/haproxy $HOME/.local/etc/init.d/haproxy $HOME/.local/var/log/haproxy

if [ $NOBACKUP ]; then rm -f "$HBP"/nrp-frontend/public/config.js.bak*; else backup "$HBP"/nrp-frontend/config/config.js; fi
rm -f "$HBP"/nrp-frontend/src/config.js.local
if [ $NOBACKUP ]; then rm -f "$HBP"/nrp-proxy/config.json.bak*; else backup "$HBP"/nrp-proxy/config.json; fi
rm -f "$HBP"/nrp-proxy/config.json.local
echo "DONE"
