#!/bin/bash

cd $HBP || { echo ERROR;exit 1; }
source $HBP/user-scripts/servers.txt || { echo ERROR;exit 1; }
source $HBP/user-scripts/nrp_functions || { echo ERROR;exit 1; }

ispuppet="no"
if [ "$1" = "puppet" ]
then
  ispuppet="yes"
  shift
fi

if [ $# -lt 1 ]
then
  echo "Usage: "$0" [puppet] dev|staging|<list of machines>"
  exit 1
fi

if [ $1 = "staging" ]
then
  servers=(
  ${staging_servers[*]}
  )
elif [ $1 = "dev" ]
then
  servers=(
  ${dev_servers[*]}
  )
else
  servers=("$*")
fi

function puppetagentall() {
    echo "Running puppet agent for $1"
    touch "$touchfilebase""$1"
    ssh -o 'BatchMode yes' -K root@$1 /bin/bash << EOF
        puppet agent --test
        chown bbpnrsoa /etc/krb5.keytab.d/bbpnrsoa.keytab
        echo ------------------------------------------------------------
EOF
     rm "$touchfilebase""$1"
}

function nrprestart() {
    echo "Restarting $1"
    touch "$touchfilebase""$1"
    ssh -o 'BatchMode yes' -K root@$1 /bin/bash << EOF
        supervisorctl stop all
        sleep 2
        nohup supervisorctl start all &>/dev/null 2>&1
        sleep 2
        nohup /etc/init.d/nginx-lua restart &>/root/restart.log 2>&1
        sleep 2
        echo
        echo ------------------------------------------------------------
        echo $1
        supervisorctl status
        cat /root/restart.log
        echo ------------------------------------------------------------
EOF
     rm "$touchfilebase""$1"
}


rm -f /tmp/nrprestart-*
rm -f /tmp/nrpcheckssh
touchfilebase="/tmp/nrprestart-"`date '+%H%M%S'`"-"
touch /tmp/nrpcheckssh

for var in ${servers[@]}
do
      checkssh $var /tmp/nrpcheckssh &
      sleep 0.5
done

waitforall "checking"

waserror=`cat /tmp/nrpcheckssh`

if [ -z "$waserror" ]
then
  for var in ${servers[@]}
  do
     if [ $ispuppet = "yes" ]
     then
        puppetagentall $var &
     else
        nrprestart $var &
     fi
     sleep 1
  done
  waitforall "restarting"
else
  echo ------------------------------------------------------------
  echo "You have offendings keys in your known_host file."
  echo 'Remove keys using sed #d ~/.ssh/known_hosts where # is'
  echo 'the mentioned line number. Then manually ssh on the'
  echo 'mentioned machines to set the new RSA key and rerun this script'
  echo ------------------------------------------------------------
fi

rm -f /tmp/nrprestart-*
rm -f /tmp/nrpcheckssh
echo "Finished"
