#!/bin/bash
# This script gives many NRP updating options to users
source $HBP/user-scripts/nrp_functions || { echo ERROR;exit 1; }

function help {
  echo "Usage: "`basename $0`" <command> [<arg>]"
  echo "  If arg='all', include 3rd party repos (gazebo, opensim, nest, ...)"
  echo "  Command can be:"
  echo "    help    : Print this message"
  echo "    rebase  : Switch repos to master and rebase"
  echo "    build   : Build all buildable repos (except 3rd party)"
  echo "              Requires VPN connection"
  echo "    update  : Run rebase followed by build"
  echo "              You will be prompted for running configure_nrp"
  echo "              Requires connection to the EPFL VPN"
  echo "    itmaster: Rebases your NRP and create a clean IT branch in each repo"
  echo "    gitclean: Removes all local branches except master"
}

if [ $# -lt 1 ]; then help;exit 1; fi
command="$1"
arg="$2"

case "$command" in
"rebase")
  nrp_rebase $arg
  ;;
"build")
  nrp_build $arg
  ;;
"update")
  nrp_rebase $arg
  nrp_build $arg
  nrp_configure
  ;;
"itmaster")
  nrp_rebase $arg
  it_branch $arg
  ;;
"gitclean")
  clean_branches $arg
  ;;
*)
  help
  ;;
esac
